### ISSUE TITLE
What is the DBL token? 

### ISSUE THREAD

**Issue by Mystik01** [atomheartother/A-I-kyan#71]
Hi,
I'm setting the bot for myself and in the env file it's asking for a DBL token, I don't know what that is or where to find it... Where do I get it from?

**Comment by atomheartother** [comment]
`DBL Token` is for the Discord Bot List, you don't need it until you wanna put your bot on discord bot list ^^

You're not the first to ask, I'll have to go through `.env` and add more comments.

**Comment by Mystik01** [comment]
@atomheartother thanks sir for the info!
