### ISSUE TITLE
Publish Docker image onto Docker Hub

### ISSUE THREAD

**Issue by saitho** [atomheartother/A-I-kyan#75]
I noticed you're providing a Dockerfile but I couldn't find a Docker image on Docker Hub.
Can you publish one, so that for setting up a custom instance of QTweet one can directly pull the container without having to clone the repository?

**Comment by atomheartother** [comment]
You know, this is one of those things I keep saying I'll eventually do and never actually end up doing. I'll do it right now, but i'll also write some documentation to do it with this method so it might take longer than just "push it".

**Comment by saitho** [comment]
One could set up a CI workflow that automatically publishes to Docker Hub when a new release is created.
You could use GitHub actions for that. :) If you need help I could also send that as PR, I've already done that.

**Comment by atomheartother** [comment]
Absolutely submit that PR, it'll save me time ^^ I already have a docker account so it'll only be a matter of linking the repos

**Comment by saitho** [comment]
Oh right, you can set that up within Docker Hub.
It now also has build rules which enable building from tagged releases.
Simply creating a new repository on Docker Hub and linking it to this one should do the trick.
No need of any additional configuration in the repository.

**Comment by atomheartother** [comment]
Yep, i just thought there were changes to do in the repo but I guess not! Ok lemme give this a shot and I'll get back to you ^^

**Comment by atomheartother** [comment]
Ah wait, we're gonna run into a problem, QTweet currently relies on `.env` values fed through `docker-compose` in its build process, so i do need to change a few things.

**Comment by saitho** [comment]
Adding a `VOLUME` on the root directory should enable one to mount an .env file via Docker Compose or `docker run`.

**Comment by atomheartother** [comment]
Oh no, i mean the env is necessary at *build time*, and don't worry i fixed it, as much as it can be fixed anyway.

Updated documentation: https://docs.google.com/document/d/1LGxfhxptioc653pqJaY5owwpZmzTg4rggqwBYcgO73I/edit#heading=h.anaydnlsghus

Let me know if it works, obviously this is untested.

**Comment by saitho** [comment]
Yes, works fine. Thanks!
